CREATE TABLE AddressDetail(
	AddressId INT NOT NULL IDENTITY(1,1),
	HomeAddress VARCHAR(200) NOT NULL,
	Country VARCHAR (50) NOT NULL,
	State VARCHAR(20) NOT NULL,
	City VARCHAR(50) NOT NULL,
	Zip VARCHAR(10) NOT NULL,
	PRIMARY KEY(AddressId),
	UserId INT FOREIGN KEY REFERENCES 
	[User] (UserId)
);